# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-16 01:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20161216_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='edited',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
