# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-16 00:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0002_auto_20161216_0320'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleRatingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.SmallIntegerField(default=0)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('edited', models.DateTimeField(default=django.utils.timezone.now)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='articles.Article')),
            ],
        ),
    ]
