# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-16 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('edited', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('session', models.CharField(editable=False, max_length=40)),
                ('ip', models.CharField(editable=False, max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='articleratingmodel',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='articleratingmodel',
            name='edited',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='vote',
            name='article_rating_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.ArticleRatingModel'),
        ),
    ]
