# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-17 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('rating', '0003_auto_20161216_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.SlugField()),
                ('score', models.SmallIntegerField(default=0)),
                ('likes', models.SmallIntegerField(default=0)),
                ('dislikes', models.SmallIntegerField(default=0)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('edited', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='tied object')),
            ],
        ),
        migrations.RemoveField(
            model_name='articleratingmodel',
            name='article',
        ),
        migrations.AlterField(
            model_name='vote',
            name='article_rating_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.RatingModel'),
        ),
        migrations.DeleteModel(
            name='ArticleRatingModel',
        ),
    ]
