# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-17 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0004_auto_20161217_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='article_rating_model',
            new_name='rating_model',
        ),
    ]
