# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-17 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.TextField(editable=False),
        ),
    ]
