# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-16 01:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hitcount',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='articles.Article'),
        ),
    ]
